#!/usr/bin/env bash

echo -e "Content-Type: text/html;charset=utf-8\n\n"
echo -e "<!DOCTYPE html>"
echo -e "<html lang=\"en\">"
echo -e "<head>"
echo -e "<title>~/paperjam</title>"
echo -e "<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\"/>"
echo -e "<script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js\"></script>"
echo -e "<link href=\"../css/css.css\" rel=\"stylesheet\" type=\"text/css\">"
echo -e "<script src=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js\"></script>"
echo -e "<script src=\"../js/js.js\"></script>"
echo -e "<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">"
echo -e "</head>"
echo -e "<body>"
echo -e "<div class=\"container-fluid\">"
echo -e "<h3>Bash CGI script</h3>"
echo -e "<p class=\"text-vertical-center\">&nbsp;</p>"
echo -e "<h6><b>`basename ${BASH_SOURCE[0]}` says:</b>Hello CGI!</h6>"
echo -e "<h6><b>UNIX Epoch is:</b> `date +%s`</h6>"
echo -e "<h6><b>Date is:</b> `date`</h6>"
echo -e "<h6><b>The System is:</b> `uname -a`</h6>"
echo -e "<a href="../">back</a>"
echo -e "</div>"
echo -e "<footer>"
echo -e "<p>"
echo -e "<a href=\"https://plus.google.com/u/0/109449761845014157264\"><i class=\"fa fa-google-plus fa-fw fa-1x\"></i></a>"
echo -e "<a href=\"http://www.facebook.com/michael.tsouchlarakis\"><i class=\"fa fa-facebook fa-fw fa-1x\"></i></a>"
echo -e "<a href=\"https://github.com/MichaelTd\"><i class=\"fa fa-github fa-fw fa-1x\"></i></a>"
echo -e "<a href=\"https://www.linkedin.com/in/michael-tsouchlarakis/\"><i class=\"fa fa-linkedin fa-fw fa-1x\"></i></a>"
echo -e "<a href=\"https://twitter.com/tsouchlarakis\"><i class=\"fa fa-twitter fa-fw fa-1x\"></i></a>"
echo -e "<a href=\"http://codepen.io/TdMichael/\"><i class=\"fa fa-codepen fa-1x\"></i></a>"
echo -e "<a href=\"https://www.freecodecamp.com/michaeltd/\"><i class=\"fa fa-free-code-camp fa-fw fa-1x\"></i></a>"
echo -e "<a href=\"mailto:tsouchlarakis@gmail.com\"><i class=\"fa fa-envelope fa-fw fa-1x\"></i></a>"
echo -e "<a href=\"https://www.minds.com/michaeltsouchlarakis\">TDM</a>"
echo -e "<script type=\"text/javascript\">var year = new Date();document.write(year.getFullYear());</script>"
echo -e "</p></footer></body></html>"
